# In this section, you can handle some settings to customize your plugin.
settings:
  # The standard provider is 'Yaml'. All data will be saved locally in a file.
  # We recommend saving the data with a database like 'MySQL' or 'MongoDB'.
  provider: Yaml

  # Decide which message file should be loaded and used to display messages. The name of the file must be specified, and it must be located in the 'lang' folder.
  # Examples: 'en-us' for the American translation; 'de-de' for the German translation.
  # You can customize these files or create your own language file by copying and renaming them.
  lang: 'en-us'

  # All data from this plugin is stored temporarily in a cache. To update this cache when something changes, there is an update interval.
  # Specify in seconds after how many seconds this cache should be updated.
  # It is not possible to set this value below 30 seconds due to possible performance issues.
  # If you run this plugin on one single server: Set this value to '0' if you want to disable the update interval.
  update-interval: 60

  # Enable or disable the warning limit. If a player has more active warnings than the provided limit, the player will
  # be automatically banned. Here you can specify the limit, the ban reason and duration.
  warn-limit:
    enable: true
    limit: 5
    ban-reason: "You reached the warning limit"
    ban-duration: 5d12h

# In this section, you can define default values for reasons and durations of punishments.

# Possible time formats:
# Permanent = -1
# 30 minutes = 30m
# 1 hour = 1h
# 1 day = 1d
# 5,5 days = 5d12h
# Time-Format: 3d2h1m

# Preset-Format: id:reason:time-format
presets:
  ban:
    - 1:Hacking:1d12h
    - 2:Insults:8h
  mute:
    - 1:Spamming:30m
    - 2:Insults:2h
    - 3:Advertisement:2d12h
  warning:
    - 1:Chat behavior:7d
    - 2:Insults:10d12h

# If you set the provider to 'MongoDB', please specify the connection uri and the database.
mongodb:
  uri: "mongodb://<user>:<password>@<ipAddress>:27017/"
  database: "punishments"

# If you set the provider to 'MySQL', please specify the needed data to connect to your MySQL database.
mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  database: "punishments"
  password: "strongpassword"

# This plugin stores the credentials for the database only in this file. The plugin uses this data only to
# connect to the databases. This data is not shared or stored for other applications.

# Here you can edit all command names, descriptions, aliases and permissions.
commands:
  ban:
    name: "ban"
    description: "Ban a player temporarily for a certain reason."
    aliases: [ "pban" ]
    permission: "punishments.command.ban"
  banlog:
    name: "banlog"
    description: "Get a history of all bans of this player."
    aliases: [ "blog", "banhistory" ]
    permission: "punishments.command.banlog"
  checkban:
    name: "checkban"
    description: "Check if a player is banned and get more information."
    aliases: [ "cban", "isbanned" ]
    permission: "punishments.command.checkban"
  editban:
    name: "editban"
    description: "Change the duration or the reason for a punishment."
    aliases: [ "eban", "updateban" ]
    permission: "punishments.command.editban"
  tempban:
    name: "tempban"
    description: "Ban a player temporarily for a certain reason."
    aliases: [ "tban", "timeban" ]
    permission: "punishments.command.tempban"
  unban:
    name: "unban"
    description: "Cancel a punishment."
    aliases: [ "uban", "cancelban", "removeban" ]
    permission: "punishments.command.unban"
  mute:
    name: "mute"
    description: "Mute a player temporarily for a certain reason."
    aliases: [ "pmute" ]
    permission: "punishments.command.mute"
  mutelog:
    name: "mutelog"
    description: "Get a history of all mutes of this player."
    aliases: [ "mlog", "mutehistory" ]
    permission: "punishments.command.mutelog"
  checkmute:
    name: "checkmute"
    description: "Check if a player is muted and get more information."
    aliases: [ "cmute", "ismuted" ]
    permission: "punishments.command.checkmute"
  editmute:
    name: "editmute"
    description: "Change the duration or the reason for a punishment."
    aliases: [ "emute", "updatemute" ]
    permission: "punishments.command.editmute"
  tempmute:
    name: "tempmute"
    description: "Mute a player temporarily for a certain reason."
    aliases: [ "tmute", "timemute" ]
    permission: "punishments.command.tempmute"
  unmute:
    name: "unmute"
    description: "Cancel a punishment."
    aliases: [ "umute", "cancelmute", "removemute" ]
    permission: "punishments.command.unmute"
  editwarning:
    name: "editwarning"
    description: "Change the duration or the reason for a warning."
    aliases: [ "ewarn", "updatewarning" ]
    permission: "punishments.command.editwarning"
  tempwarn:
    name: "tempwarn"
    description: "Warn a player temporarily for a certain reason."
    aliases: [ "twarn", "timewarn" ]
    permission: "punishments.command.tempwarn"
  unwarn:
    name: "unwarn"
    description: "Cancel a warning."
    aliases: [ "uwarn", "cancelwarning", "removewarning" ]
    permission: "punishments.command.unwarn"
  warn:
    name: "warn"
    description: "Warn a player temporarily for a certain reason."
    aliases: [ "pwarn" ]
    permission: "punishments.command.warn"
  warnings:
    name: "warnings"
    description: "Get all active warnings of this player."
    aliases: [ "activewarnings", "aw" ]
    permission: "punishments.command.warnings"
  warnlog:
    name: "warnlog"
    description: "Get a history of all warnings of this player."
    aliases: [ "wlog", "warninghistory" ]
    permission: "punishments.command.warnlog"
  checkpunishment:
    name: "checkpunishment"
    description: "Check if a punishment id exists and get data."
    aliases: [ "cp", "checkid" ]
    permission: "punishments.command.checkpunishment"
  clearlog:
    name: "clearlog"
    description: "Clear a certain log type of a player."
    aliases: [ "clog", "deletelog" ]
    permission: "punishments.command.clearlog"
  deletepunishment:
    name: "deletepunishment"
    description: "Delete a certain log entry of a player by the log id."
    aliases: [ "dlog", "deletelog" ]
    permission: "punishments.command.deletepunishment"

# Do not edit the config version!
version: 1