# In this section, you can handle some settings to customize your plugin.
settings:
  # The standard provider is 'Yaml'. All data will be saved locally in a file.
  # We recommend saving the data with a database like 'MySQL' or 'MongoDB'.
  provider: Yaml

  # Decide which message file should be loaded and used to display messages. The name of the file must be specified, and it must be located in the 'lang' folder.
  # Examples: 'en-us' for the American translation; 'de-de' for the German translation.
  # You can customize these files or create your own language file by copying and renaming them.
  lang: 'en-us'

  # All data from this plugin is stored temporarily in a cache. To update this cache when something changes, there is an update interval.
  # Specify in seconds after how many seconds this cache should be updated.
  # It is not recommended to set this value below 30 seconds due to possible performance issues.
  # If you run this plugin on one single server: Set this value to '0' if you want to disable the update interval.
  update-interval: 45

# In this section, you can define default values for reasons and durations of punishments.
# -1 = Permanent
# 1 hour = 60 minutes
# 1 day = 1440 minutes
# 1 week = 10080 minutes
# 1 month = 43800 minutes
# 1 year = 525600 minutes
presets:
  ban:
    - 1:Hacking:120
    - 2:Insults:60
  mute:
    - 1:Spamming:30
    - 2:Insults:120
    - 3:Advertisement:240
  warning:
    - 1:Chat behavior:1440
    - 2:Insults:2880

# If you set the provider to 'MongoDB', please specify the connection uri and the database.
mongodb:
  uri: "mongodb://<user>:<password>@<ipAddress>:27017/"
  database: "punishments"

# If you set the provider to 'MySQL', please specify the needed data to connect to your MySQL database.
mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  database: "punishments"
  password: "strongpassword"

# This plugin stores the credentials for the database only in this file. The plugin uses this data only to
# connect to the databases. This data is not shared or stored for other applications.

# Here you can edit all command names, descriptions, aliases and permissions.
commands:
  tempban:
    name: "tempban"
    description: "Ban a player temporarily for a certain reason."
    aliases: [ "tban", "timeban" ]
    permission: "punishments.command.tempban"

# Do not edit the config version!
version: 1